# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageTCP.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10MessageTCP.proto\"\x9d\x01\n\nMessageTCP\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\x05\x12\r\n\x05model\x18\x02 \x01(\t\x12\x13\n\x0b\x61gent_input\x18\x03 \x03(\x02\x12\x11\n\tenv_state\x18\x04 \x03(\x02\x12\x0e\n\x06reward\x18\x05 \x01(\x01\x12\x0c\n\x04\x64one\x18\x06 \x01(\x08\x12\x15\n\rfunction_call\x18\x07 \x01(\t\x12\x11\n\tdebug_msg\x18\x08 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MessageTCP_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGETCP._serialized_start=21
  _MESSAGETCP._serialized_end=178
# @@protoc_insertion_point(module_scope)
